import type { Locale } from "./portfolio";

export const adminArticlesCopy = {
  en: {
    tabContactLabel: "Inquiries",
    tabArticlesLabel: "Articles",
    panelLabel: "articles://manage",
    title: "Articles",
    description:
      "Write, edit, and publish bilingual articles. Each article carries an English and a Thai translation.",
    listLabel: "All articles",
    newArticleLabel: "New article",
    searchLabel: "Search",
    searchPlaceholder: "Search by title, slug, or category",
    statusFilterLabel: "Filter status",
    statusAllLabel: "All",
    statusDraftLabel: "Draft",
    statusPublishedLabel: "Published",
    emptyLabel: "No articles yet. Create your first one.",
    loadingLabel: "Loading...",
    refreshLabel: "Refresh",
    slugLabel: "Slug",
    slugPlaceholder: "auto-generated from the English title if left blank",
    categoryLabel: "Category",
    categoryPlaceholder: "Frontend systems",
    statusLabel: "Status",
    updatedLabel: "Updated",
    publishedAtLabel: "Published",
    editLabel: "Edit",
    deleteLabel: "Delete",
    deletingLabel: "Deleting...",
    confirmDeleteLabel: "Delete this article? This cannot be undone.",
    cancelLabel: "Cancel",
    saveLabel: "Save article",
    savingLabel: "Saving...",
    createdMessage: "Article created.",
    updatedMessage: "Article updated.",
    deletedMessage: "Article deleted.",
    translationEnLabel: "English",
    translationThLabel: "Thai",
    fieldTitleLabel: "Title",
    fieldSummaryLabel: "Summary",
    fieldLeadLabel: "Lead",
    fieldReadingTimeLabel: "Reading time",
    fieldReadingTimePlaceholder: "6 min",
    sectionsLabel: "Sections",
    sectionHeadingLabel: "Heading",
    sectionParagraphLabel: "Paragraph",
    addSectionLabel: "Add section",
    removeSectionLabel: "Remove section",
    addParagraphLabel: "Add paragraph",
    removeParagraphLabel: "Remove paragraph",
    requestFailedLabel: "The request could not be completed right now.",
    validationFailedLabel: "Please fix the highlighted fields.",
    viewPublicLabel: "View",
  },
  th: {
    tabContactLabel: "ข้อความติดต่อ",
    tabArticlesLabel: "บทความ",
    panelLabel: "articles://manage",
    title: "บทความ",
    description: "เขียน แก้ไข และเผยแพร่บทความสองภาษา แต่ละบทความมีทั้งฉบับภาษาอังกฤษและภาษาไทย",
    listLabel: "บทความทั้งหมด",
    newArticleLabel: "บทความใหม่",
    searchLabel: "ค้นหา",
    searchPlaceholder: "ค้นหาจากหัวข้อ slug หรือหมวดหมู่",
    statusFilterLabel: "กรองสถานะ",
    statusAllLabel: "ทั้งหมด",
    statusDraftLabel: "ฉบับร่าง",
    statusPublishedLabel: "เผยแพร่แล้ว",
    emptyLabel: "ยังไม่มีบทความ เริ่มเขียนบทความแรกได้เลย",
    loadingLabel: "กำลังโหลด...",
    refreshLabel: "รีเฟรช",
    slugLabel: "Slug",
    slugPlaceholder: "ถ้าเว้นว่างจะสร้างจากหัวข้อภาษาอังกฤษให้อัตโนมัติ",
    categoryLabel: "หมวดหมู่",
    categoryPlaceholder: "Frontend systems",
    statusLabel: "สถานะ",
    updatedLabel: "แก้ไขล่าสุด",
    publishedAtLabel: "เผยแพร่",
    editLabel: "แก้ไข",
    deleteLabel: "ลบ",
    deletingLabel: "กำลังลบ...",
    confirmDeleteLabel: "ลบบทความนี้ใช่ไหม การลบไม่สามารถย้อนกลับได้",
    cancelLabel: "ยกเลิก",
    saveLabel: "บันทึกบทความ",
    savingLabel: "กำลังบันทึก...",
    createdMessage: "สร้างบทความแล้ว",
    updatedMessage: "อัปเดตบทความแล้ว",
    deletedMessage: "ลบบทความแล้ว",
    translationEnLabel: "ภาษาอังกฤษ",
    translationThLabel: "ภาษาไทย",
    fieldTitleLabel: "หัวข้อ",
    fieldSummaryLabel: "สรุป",
    fieldLeadLabel: "ย่อหน้านำ",
    fieldReadingTimeLabel: "เวลาอ่าน",
    fieldReadingTimePlaceholder: "6 นาที",
    sectionsLabel: "หัวข้อย่อย",
    sectionHeadingLabel: "หัวข้อ",
    sectionParagraphLabel: "ย่อหน้า",
    addSectionLabel: "เพิ่มหัวข้อย่อย",
    removeSectionLabel: "ลบหัวข้อย่อย",
    addParagraphLabel: "เพิ่มย่อหน้า",
    removeParagraphLabel: "ลบย่อหน้า",
    requestFailedLabel: "ไม่สามารถดำเนินการได้ในขณะนี้",
    validationFailedLabel: "โปรดแก้ไขช่องที่ถูกไฮไลต์",
    viewPublicLabel: "ดูหน้าเว็บ",
  },
} as const satisfies Record<Locale, Record<string, string>>;

export type AdminArticlesCopy = (typeof adminArticlesCopy)[Locale];
