export type Locale = "en" | "th";

export type PortfolioDictionary = {
  meta: {
    metaTitle: string;
    metaDescription: string;
    openGraphTitle: string;
    openGraphDescription: string;
  };
  ui: {
    brandRole: string;
    languageLabel: string;
    menuLabel: string;
    closeMenuLabel: string;
    contactCta: string;
    sessionLabel: string;
    profilePreviewLabel: string;
    statsLabel: string;
    linksLabel: string;
    legalLabel: string;
    stackLabel: string;
    currentRoleLabel: string;
    channelsLabel: string;
    availabilityLabel: string;
    profileImageAlt: string;
    commands: {
      boot: string;
      whoami: string;
      role: string;
      focus: string;
      status: string;
      about: string;
      work: string;
      skills: string;
      experience: string;
      chat: string;
      contact: string;
    };
  };
  hero: {
    badge: string;
    heroTitle: string;
    heroText: string;
    heroKicker: string;
    heroNote: string;
    viewWork: string;
    downloadResume: string;
    contactMe: string;
    focusedTitle: string;
    focusedText: string;
  };
  sections: {
    aboutEyebrow: string;
    aboutTitle: string;
    aboutText: string;
    principles: string[];
    workEyebrow: string;
    workTitle: string;
    workText: string;
    featuredWork: Array<{
      eyebrow: string;
      title: string;
      description: string;
      bullets: string[];
      stack: string[];
    }>;
    ecosystemEyebrow: string;
    ecosystemTitle: string;
    ecosystemText: string;
    ecosystemRepositories: Array<{
      eyebrow: string;
      title: string;
      description: string;
      bullets: string[];
      stack: string[];
      href: string;
    }>;
    skillsEyebrow: string;
    skillsTitle: string;
    skillsText: string;
    skills: Array<{ group: string; list: string }>;
    experienceEyebrow: string;
    experienceRoles: Array<{
      roleTitle: string;
      company: string;
      timeline: string;
      bullets: string[];
    }>;
    chatEyebrow: string;
    chatTitle: string;
    chatText: string;
    contactEyebrow: string;
    contactTitle: string;
    contactText: string;
  };
  legal: {
    shared: {
      effectiveLabel: string;
      updatedLabel: string;
      contactLabel: string;
      intro: string;
      backToHome: string;
    };
    directory: {
      eyebrow: string;
      title: string;
      text: string;
      termsLabel: string;
      termsHelp: string;
      privacyLabel: string;
      privacyHelp: string;
      validationMessage: string;
    };
    terms: {
      title: string;
      description: string;
      intro: string;
      sections: Array<{
        heading: string;
        body: string[];
      }>;
    };
    privacy: {
      title: string;
      description: string;
      intro: string;
      sections: Array<{
        heading: string;
        body: string[];
      }>;
    };
  };
  chat: {
    launcherLabel: string;
    openLabel: string;
    chatTabLabel: string;
    closeLabel: string;
    windowTitle: string;
    quickPrompts: string[];
    inputPlaceholder: string;
    sendLabel: string;
    assistantName: string;
    userName: string;
    newChatLabel: string;
    recentChatsLabel: string;
    recentChatsEmptyLabel: string;
    latestChatLabel: string;
    loadingLatestChatLabel: string;
    latestChatEmptyLabel: string;
    deleteChatLabel: string;
    emptyState: string;
    streamError: string;
    requestHumanLabel: string;
    requestingHumanLabel: string;
    humanRequestedLabel: string;
    starterConversation: Array<{
      role: "assistant" | "user";
      text: string;
    }>;
  };
  contactLabels: {
    email: string;
    github: string;
    linkedin: string;
    line: string;
    resume: string;
  };
  contactForm: {
    panelLabel: string;
    title: string;
    description: string;
    nameLabel: string;
    namePlaceholder: string;
    emailLabel: string;
    emailPlaceholder: string;
    companyLabel: string;
    companyPlaceholder: string;
    subjectLabel: string;
    subjectPlaceholder: string;
    messageLabel: string;
    messagePlaceholder: string;
    storageNote: string;
    submitLabel: string;
    submittingLabel: string;
    submitSuccess: string;
    submitError: string;
  };
  socialLinks: {
    github: string;
    linkedin: string;
  };
  navItems: Array<{ id: string; label: string }>;
  stats: Array<{ value: string; label: string }>;
  footer: {
    copyright: string;
  };
  articleDirectory: {
    navLabel: string;
    eyebrow: string;
    title: string;
    description: string;
    featuredLabel: string;
    listLabel: string;
    readArticleLabel: string;
    backToArticlesLabel: string;
    backToPortfolioLabel: string;
    publishedLabel: string;
    readingTimeLabel: string;
    emptyLabel: string;
  };
  adminWorkspace: {
    navLabel: string;
    eyebrow: string;
    title: string;
    description: string;
    backToPortfolioLabel: string;
    authPanelLabel: string;
    authTitle: string;
    authDescription: string;
    emailLoginLabel: string;
    emailLoginPlaceholder: string;
    passwordLabel: string;
    passwordPlaceholder: string;
    signInLabel: string;
    signingInLabel: string;
    signOutLabel: string;
    signingOutLabel: string;
    signedInMessage: string;
    signedOutMessage: string;
    authRequiredMessage: string;
    authInvalidMessage: string;
    authCheckingLabel: string;
    loadLabel: string;
    loadingLabel: string;
    inquiriesLabel: string;
    listControlsLabel: string;
    searchLabel: string;
    searchPlaceholder: string;
    statusFilterLabel: string;
    statusAllLabel: string;
    pageLabel: string;
    previousPageLabel: string;
    nextPageLabel: string;
    resultsLabel: string;
    currentUserLabel: string;
    roleLabel: string;
    roleAdminLabel: string;
    roleEditorLabel: string;
    roleViewerLabel: string;
    permissionsReadOnlyLabel: string;
    permissionsWriteLabel: string;
    permissionsManageUsersLabel: string;
    detailsLabel: string;
    workflowLabel: string;
    sessionsLabel: string;
    sessionsEmptyLabel: string;
    sessionsCurrentLabel: string;
    revokeSessionLabel: string;
    revokingSessionLabel: string;
    logoutEverywhereLabel: string;
    loggingOutEverywhereLabel: string;
    sessionsUpdatedMessage: string;
    usersLabel: string;
    usersEmptyLabel: string;
    saveRoleLabel: string;
    savingRoleLabel: string;
    roleUpdatedMessage: string;
    historyLabel: string;
    historyEmptyLabel: string;
    historyCreatedLabel: string;
    historyStatusUpdatedLabel: string;
    historyNoteUpdatedLabel: string;
    historyStatusAndNoteUpdatedLabel: string;
    historyFromLabel: string;
    historyToLabel: string;
    historyByLabel: string;
    historyNoteBeforeLabel: string;
    historyNoteAfterLabel: string;
    summaryLabel: string;
    emptyLabel: string;
    summaryEmptyLabel: string;
    generateSummaryLabel: string;
    generatingSummaryLabel: string;
    saveChangesLabel: string;
    savingChangesLabel: string;
    savedChangesMessage: string;
    nameLabel: string;
    emailLabel: string;
    companyLabel: string;
    subjectLabel: string;
    localeLabel: string;
    deliveryLabel: string;
    statusLabel: string;
    internalNoteLabel: string;
    internalNotePlaceholder: string;
    handledAtLabel: string;
    createdAtLabel: string;
    messageLabel: string;
    summaryPromptLabel: string;
    summaryResultLabel: string;
    statusNewLabel: string;
    statusInProgressLabel: string;
    statusHandledLabel: string;
    requestFailedLabel: string;
  };
  adminArticles: {
    tabContactLabel: string;
    tabArticlesLabel: string;
    tabChatLabel: string;
    panelLabel: string;
    title: string;
    description: string;
    listLabel: string;
    newArticleLabel: string;
    searchLabel: string;
    searchPlaceholder: string;
    statusFilterLabel: string;
    statusAllLabel: string;
    statusDraftLabel: string;
    statusPublishedLabel: string;
    emptyLabel: string;
    loadingLabel: string;
    refreshLabel: string;
    slugLabel: string;
    slugPlaceholder: string;
    categoryLabel: string;
    categoryPlaceholder: string;
    statusLabel: string;
    updatedLabel: string;
    publishedAtLabel: string;
    editLabel: string;
    deleteLabel: string;
    deletingLabel: string;
    confirmDeleteLabel: string;
    cancelLabel: string;
    saveLabel: string;
    savingLabel: string;
    createdMessage: string;
    updatedMessage: string;
    deletedMessage: string;
    translationEnLabel: string;
    translationThLabel: string;
    fieldTitleLabel: string;
    fieldSummaryLabel: string;
    fieldLeadLabel: string;
    fieldReadingTimeLabel: string;
    fieldReadingTimePlaceholder: string;
    contentLabel: string;
    contentPlaceholder: string;
    contentHelp: string;
    requestFailedLabel: string;
    validationFailedLabel: string;
    viewPublicLabel: string;
  };
  notFound: {
    badge: string;
    heading: string;
    text: string;
    homeEnLabel: string;
    homeThLabel: string;
  };
  errorPage: {
    badge: string;
    heading: string;
    text: string;
    retryLabel: string;
  };
};

export const locales = ["en", "th"] as const satisfies readonly Locale[];
export const defaultLocale: Locale = "en";

export function hasLocale(value: string): value is Locale {
  return locales.includes(value as Locale);
}
